name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  config: Release
  solutionDir: Azure.ServiceBus.Queue.MessageReprocessor

jobs:
  build:
    name: 'Build CLI'
    runs-on: ${{ matrix.os }}
    env:
      # don't print dotnet logo
      DOTNET_NOLOGO: true
      # disable telemetry (reduces dotnet tool output in logs)
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    strategy:
      # let us get failures from other jobs even if one fails
      fail-fast: false

      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        include:
        - os: 'windows-latest'
          rid: 'win-x64'
          configuration: 'release'
          publishLanguageServer: 'false'
        - os: 'ubuntu-latest'
          rid: 'linux-x64'
          configuration: 'release'
          publishLanguageServer: 'true'
        - os: 'macos-latest'
          rid: 'osx-x64'
          configuration: 'release'
          publishLanguageServer: 'false'

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies

      run: dotnet restore $solutionDir

    - name: Build
      run: dotnet build --configuration $config --no-restore $solutionDir

    - name: Test
      run: dotnet test --configuration $config --no-restore --verbosity normal --collect:"XPlat Code Coverage" $solutionDir
      
    - name: Upload Code Coverage
      uses: codecov/codecov-action@v1
      with:
        flags: dotnet
