name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  config: Release
  solutionDir: Azure.ServiceBus.Queue.MessageReprocessor

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore $solutionDir
    - name: Build
      run: dotnet build --configuration $config --no-restore $solutionDir
    - name: Test
      run: dotnet test --configuration $config --no-restore --verbosity normal $solutionDir
